version: "3.9"

services:
  ia-api:
    image: node:20-alpine
    container_name: ia-api-dev
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      corepack enable &&
      corepack prepare pnpm@latest --activate &&
      pnpm install &&
      pnpm run dev
      "
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    mem_limit: 700m
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-dev
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data_dev:/qdrant/storage

volumes:
  qdrant_data_dev: